### PR TITLE
Add Chinese character tests for isPunct

### PR DESCRIPTION
**Pull request by Real-John-Cheung**
refer to https://github.com/dhowe/rita/issues/52

Tests failed

### CODE REVIEW

**Comment by dhowe** [comment]
do you mean that Chinese characters are being marked as punctuation ?

**Comment by Real-John-Cheung** [comment]
yes, RiTa.isPunct(chineseCharacter) return true

**Comment by dhowe** [comment]
ok. lets create a ticket for this (the regex probably needs to be changed) in the rita repo
pls make sure this PR doesn't cause any tests to fail (besides known-issues)

also add the test to js known issues

**Comment by Real-John-Cheung** [comment]
the ticket is here https://github.com/dhowe/rita/issues/79

**Comment by Real-John-Cheung** [comment]
above commit should fix https://github.com/dhowe/rita/issues/79

**Pull request merged**
